// Generated by jextract

package unistd;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$15 {

    static final FunctionDescriptor revoke$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle revoke$MH = RuntimeHelper.downcallHandle(
        unistd_h.LIBRARIES, "revoke",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$15.revoke$FUNC, false
    );
    static final FunctionDescriptor profil$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_LONG,
        C_LONG,
        C_INT
    );
    static final MethodHandle profil$MH = RuntimeHelper.downcallHandle(
        unistd_h.LIBRARIES, "profil",
        "(Ljdk/incubator/foreign/MemoryAddress;JJI)I",
        constants$15.profil$FUNC, false
    );
    static final FunctionDescriptor acct$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle acct$MH = RuntimeHelper.downcallHandle(
        unistd_h.LIBRARIES, "acct",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$15.acct$FUNC, false
    );
    static final FunctionDescriptor getusershell$FUNC = FunctionDescriptor.of(C_POINTER);
    static final MethodHandle getusershell$MH = RuntimeHelper.downcallHandle(
        unistd_h.LIBRARIES, "getusershell",
        "()Ljdk/incubator/foreign/MemoryAddress;",
        constants$15.getusershell$FUNC, false
    );
    static final FunctionDescriptor endusershell$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle endusershell$MH = RuntimeHelper.downcallHandle(
        unistd_h.LIBRARIES, "endusershell",
        "()V",
        constants$15.endusershell$FUNC, false
    );
    static final FunctionDescriptor setusershell$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle setusershell$MH = RuntimeHelper.downcallHandle(
        unistd_h.LIBRARIES, "setusershell",
        "()V",
        constants$15.setusershell$FUNC, false
    );
}


