// Generated by jextract

package unistd;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$19 {

    static final MemorySegment __ILP32_OFF32_LDFLAGS$SEGMENT = CLinker.toCString("-m32", ResourceScope.newImplicitScope());
    static final MemorySegment __ILP32_OFFBIG_CFLAGS$SEGMENT = CLinker.toCString("-m32 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64", ResourceScope.newImplicitScope());
    static final MemorySegment __ILP32_OFFBIG_LDFLAGS$SEGMENT = CLinker.toCString("-m32", ResourceScope.newImplicitScope());
    static final MemorySegment __LP64_OFF64_CFLAGS$SEGMENT = CLinker.toCString("-m64", ResourceScope.newImplicitScope());
    static final MemorySegment __LP64_OFF64_LDFLAGS$SEGMENT = CLinker.toCString("-m64", ResourceScope.newImplicitScope());
    static final MemoryAddress NULL$ADDR = MemoryAddress.ofLong(0L);
}


