package de.pdbm;

import static unistd.unistd_h.*;

/**
 * Runs the C function getpid() with helper classes generated by jextract.
 * 
 * @author bernd
 *
 */
public class ProcessIdWithJextract {
	
	public static void main(String[] args) throws Throwable {
		System.out.println(getpid());
	}
	
}
